services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=mamt4real
      - MARIADB_PASSWORD=special
      - MARIADB_DATABASE=levelup_docker
      - MARIADB_ROOT_PASSWORD=my-secret-pw
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=mamt4real
      - DB_PASSWORD=special
      - DB_NAME=levelup_docker
    networks:
      - app-network
volumes:
  db-data:

networks:
  app-network:

